### ISSUE TITLE
Extend Kaleidocrypt README

### ISSUE THREAD

**Issue by anthonyanjorin** [eMoflon/kaleidoscope-zoo#8]
to explain what changes can be synchronised.  After playing around for a few minutes I still can't find out what changes to the code are actually retained after synchronising changes to the model.  How do I specify any "opaque" methods that are simply ignored and retained?  Everything I do seems to be simply deleted.

**Comment by anthonyanjorin** [comment]
How do I switch to using bxtend?

**Comment by dusko91** [comment]
You can switch to bxtend by editing this line of code:

`private final BxTool bxTool = BxTool.BXTEND;`

inside ControllerModule.
